export const cn = {
  home: {
    title: '首个NFTFi聚合协议，倡导F2P2E（免费玩赚)',
    stakingAPY: 'Staking APY',
    holders: '通证持有人数量',
    followers: 'Twitter粉丝',
    members: 'Telegram成员',
    video: '项目视频'
  },
  video: {
    title: '项目视频'
  },
  projects: {
    title: 'RamBox产品',
    subTitle1: '游戏聚合',
    subTitle2: '市场',
    subTitle3: 'DAO',
    content1:
      '鼓励优秀的GameFi团队在Gamelist上发布可玩性高、通证经济合理的GameFi项目，用户通过DAO（去中心化自律组织）投票决定是否上线项目。',
    content2:
      '用户可以在市场上购买/出售各种游戏NFT。包括角色NFT、道具NFT等，Rambox用户可以享受到 "游戏价值资本化 "所带来的便利和财富效应。',
    content3: 'RamBox平台支持RAM通证持有者自发组建DAO，进行社区治理，11Ram代币可投1票。DAO可以决定以下内容...'
  },
  tokenomics: {
    title: 'RAM通证经济',
    subTitle: 'RAM是RamBox生态系统的驱动力。',
    text1: '1.用户可以在RAMSWAP模块中质押RAM，获得RAM通证奖励。\n',
    text2: '2.用户可以在RAMSWAP模块中质押RAM-USDT的流动对，获得RAM通证奖励。\n',
    text3: '3.用户可以在GameList模块中参与各种游戏。RAM的应用场景贯穿所有游戏的经济模型中。\n',
    text4: '当用户在市场上购买/出售NFT、质押NFT或生产NFT合成资产时，可以使用RAM作为媒介，获得RAM代币奖励。',
    totalSupply: '总供应量'
  },
  partners: {
    title: '投资者和合作伙伴',
    price: 'RAM价格',
    buy: '买 RAM',
    totalSupply: '总供应量:',
    maxSupply: '最大供应量:',
    tvl: '总锁仓(TVL)'
  },
  roadmap: {
    title: '路线图',
    r1: '2022第二季度',
    r2: '2022第三季度',
    r3: '2022第四季度',
    r4: '2023第一季度',
    r5: '2023第二季度',
    r6: '2023第三季度',
    t1: '团队建设',
    t2: '项目定位和愿景',
    t3: '经济模式',
    t4: '网站',
    t5: '白皮书',
    t6: 'NFT设计',
    t7: 'RAM IDO',
    t8: '推出NFT',
    t9: 'RAM公开发行',
    t10: 'NFT权益激励池',
    t11: '创建流动池',
    t12: 'Rambox DAO',
    t13: 'Ram链公测',
    t14: '创建NFT权益社区',
    t15: '启动Ram链',
    t16: '开启节点激励',
    t17: 'NFT升级',
    t18: 'Ram链DAO',
    t19: 'RAM生态基金'
  },
  token: '代币',
  saleRule: '公平发售 - 最大买入200 USDT',
  tops: '软顶/硬顶',
  progress: '进度',
  left: 'RAM剩余总量',
  total: 'RAM总量',
  myRAM: '我的RAM令牌',
  lockup: '锁定时间',
  start: '销售开始于',
  preAddress: '预售地址',
  name: '代币名称',
  symbol: '代币符号',
  decimals: '令牌小数',
  tokenAddress: '代币地址',
  tip: '(请不要发送任何资产到合约地址！)',
  supply: '总供应量',
  presale: '用于预售的代币',
  cap: '初始市值(估计)',
  soft: '软顶',
  hard: '硬顶',
  startTime: '预售开始时间',
  endTime: '预售结束时间',
  list: '上架交易所',
  liquidityPercent: '流动性占比',
  liquidityLockupTime: '流动性锁定时间',
  days: '9天',
  enterAmount: '输入金额',
  max: '最大金额为200',
  allow: '授权 Rambox 使用你的',
  buy: '购买',
  approving: '正在授权',
  with: '使用了',
  marketplace: '市场',
  tokenomics1: '通证经济',
  insufficient: '余额不足'
}
